export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const GET_ASSESSMENTS_REQUEST = 'GET_ASSESSMENTS_REQUEST';
export const GET_GROUPS_REQUEST = 'GET_GROUPS_REQUEST';
export const GET_GROUP_MEMBERS_REQUEST = 'GET_GROUP_MEMBERS_REQUEST';
export const GET_COLORS_REQUEST = 'GET_COLORS_REQUEST';
export const SUBMIT_RESULT = 'SUBMIT_RESULT';
export const GET_GAME_INFO = 'GET_GAME_INFO';
export const GET_PARTICIPANTS_REQUEST = 'GET_PARTICIPANTS_REQUEST';
export const GET_PAST_ASSESSMENT = 'GET_PAST_ASSESSMENT';
export const GET_ASSESSMENT_DETAILS = 'GET_ASSESSMENT_DETAILS';
export const GET_FACILIATOR_INSTRUCTIONS = 'GET_FACILIATOR_INSTRUCTIONS';
export const GET_FILTERED_PARTICIPANTS = 'GET_FILTERED_PARTICIPANTS';
export const CHECK_GAME = 'CHECK_GAME';
export const SAVE_SOCKET_REF = 'SAVE_SOCKET_REF';
export const GET_LOGIN_IMG = 'GET_LOGIN_IMG';
export const GET_VIDEO = 'GET_VIDEO';
export const GET_EVENTS = 'GET_EVENTS';
export const GET_NINTY_FIVE="GET_NINTY_FIVE"


